nodeLinker: node-modules

enableGlobalCache: true

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.6.0.cjs

logFilters:
  - code: YN0013
    level: discard

compressionLevel: mixed

enableTelemetry: false

defaultSemverRangePrefix: ""

supportedArchitectures:
  cpu:
    - current
  os:
    - current
